---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.npm

env:
  - EMBER_TRY_SCENARIO=ember-release

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt

install:
  - yarn install --no-lockfile

script:
  - yarn run test
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
